########################备注信息###########################
######### 根据com.edgedo下面包结构书写下面内容  ###########
#永不执行的表达式 '-'
timetask:
  #########driver包
  demo:
    DemoTask:
      enable: false
      cron:
        #测试表达式
        test: 0/10 * * * * ?